### ISSUE TITLE
Add functionality to move caret within editor with the mouse

### ISSUE THREAD

**Issue by AlysCole** [chingu-voyage4/Bears-Team-7#23]
## :stop_sign: work in progress

**Do you want to request a *feature* or report a *bug*?**
Feature
**What is the current behavior?**
Currently, the cursor is fixed and all input is appended to the end of the text.
**If you are requesting a feature, please explain the feature in detail**
The user should be able to move the editor cursor using arrow keys and their own cursor.

### Checklist
- [x] Add functionality to move the caret using the mouse. *(Pull request #38)*
- [x] Modify existing functionality to insert new characters at the position of the caret. *(Pull request #38)*
- [x] Modify existing functionality to delete characters at the position of the caret. *(Pull request #38)*

**Comment by Matthew-Burfield** [comment]
Oh yeah! This is a good one. Any ideas on how we go about implementing this? We might have to change the logic around how we write keys to the document since at the moment we are only appending to the end.

**Comment by Matthew-Burfield** [comment]
I added this to the MVP since I feel like this is basic editor functionality - but we can discuss in the meeting this week as well

**Comment by AlysCole** [comment]
In our `data` object, I was thinking we could keep a `cursor` variable that holds the current position of the cursor.

Then, instead of simply appending to the end of the document, we can make use of string `split`/`substring` functions to insert values before the position of the cursor.
